; define global constants for the os


; constants for the kernel memory layout

    const CONST_CPU_BIT_WIDTH = 32

    const CONST_OS_CODE_START = 0xC0000000
    const CONST_OS_CODE_END = 0xCFFFFFFF

    const CONST_OS_PAGE_TABLE_LIST_START = 0xD0000000
    const CONST_OS_PAGE_TABLE_LIST_END = 0xDFFFFFFF

    const CONST_OS_PAGE_TABLE_SIZE = 0x400000
    const CONST_OS_PAGE_TABLE_BIT_SIZE = 22

    const CONST_OS_MEMORY_MAP_START = 0xE0000000
    const CONST_OS_MEMORY_MAP_END = 0xE00BFFFF

    const CONST_OS_PCB_SIZE = 0x400
    const CONST_OS_PCB_BIT_SIZE = 10

    const CONST_OS_PCB_LIST_START = 0xE00C0000
    const CONST_OS_PCB_LIST_END = 0xE00FFFFF

    const CONST_OS_PCB_MAPPING_TABLE_START = 0xE0100000
    const CONST_OS_PCB_MAPPING_TABLE_END = 0xE01003FF

    const CONST_OS_PCB_INTERRUPT_TABLE_START = 0xE0100400
    const CONST_OS_PCB_INTERRUPT_TABLE_END = 0xE01007FF

    const CONST_OS_PROCESS_WAITING_QUEUE_START = 0xE0100800
    const CONST_OS_PROCESS_WAITING_QUEUE_END = 0xE01008FF

    const CONST_OS_PROCESS_BLOCKED_QUEUE_START = 0xE0100900
    const CONST_OS_PROCESS_BLOCKED_QUEUE_END = 0xE01009FF

    const CONST_OS_CURRENT_PCB_POINTER = 0xE0100A00

    const CONST_OS_FRAME_SIZE = 0x1000
    const CONST_OS_FRAME_BIT_SIZE = 12 

    const CONST_OS_INTERRUPT_STACK_START = 0xFFFFF000
    const CONST_OS_INTERRUPT_STACK_END = 0xFFFFFFFF


; constants for the dev instruction

    const CONST_DEV_COMMAND_IO_SEEK = 0b0000000
    const CONST_DEV_COMMAND_IO_CLOSE = 0b0000001
    const CONST_DEV_COMMAND_IO_READ_BUFFER = 0b0000010
    const CONST_DEV_COMMAND_IO_WRITE_BUFFER = 0b0000011
    const CONST_DEV_COMMAND_FILE_CREATE = 0b0000100
    const CONST_DEV_COMMAND_FILE_DELETE = 0b0000101
    const CONST_DEV_COMMAND_OPEN_FILE = 0b0000110
    const CONST_DEV_COMMAND_FILE_STAT = 0b0000111
    const CONST_DEV_COMMAND_CONSOLE_PRINT_NUMBER = 0b0001000
    const CONST_DEV_COMMAND_CONSOLE_READ_NUMBER = 0b0001001
    const CONST_DEV_COMMAND_CPU_ENABLE_MEMORY_VIRTUALIZATION = 0b0001010
    const CONST_DEV_COMMAND_CPU_DISABLE_MEMORY_VIRTUALIZATION = 0b0001011

; constants for the syscall number

    const CONST_SYSCALL_FILE_READ = 0
    const CONST_SYSCALL_FILE_WRITE = 1
    const CONST_SYSCALL_FILE_OPEN = 2
    const CONST_SYSCALL_FILE_CLOSE = 3
    const CONST_SYSCALL_FILE_STAT = 4
    const CONST_SYSCALL_FILE_SEEK = 5
    const CONST_SYSCALL_FILE_CREATE = 6
    const CONST_SYSCALL_FILE_DELETE = 7    

    const CONST_SYSCALL_PROCESS_CREATE = 16
    const CONST_SYSCALL_PROCESS_EXIT = 17
    const CONST_SYSCALL_PROCESS_YIELD = 18