
; Interrupt ISR for the syscalls (0x80)
.INTERRUPTS_SYSCALLS:

    CMP $CONST_SYSCALL_FILE_READ, %eax
    JNE _INTERRUPTS_SYSCALLS_SKIP_SYSCALL_FILE_READ
    CALL SYSCALLS_FILE_READ
    JMP _INTERRUPTS_SYSCALLS_END_SYSCALL
    ._INTERRUPTS_SYSCALLS_SKIP_SYSCALL_FILE_READ:

    CMP $CONST_SYSCALL_FILE_WRITE, %eax
    JNE _INTERRUPTS_SYSCALLS_SKIP_SYSCALL_FILE_WRITE
    CALL SYSCALLS_FILE_WRITE
    JMP _INTERRUPTS_SYSCALLS_END_SYSCALL
    ._INTERRUPTS_SYSCALLS_SKIP_SYSCALL_FILE_WRITE:

    CMP $CONST_SYSCALL_FILE_OPEN, %eax
    JNE _INTERRUPTS_SYSCALLS_SKIP_SYSCALL_FILE_OPEN
    CALL SYSCALLS_FILE_OPEN
    JMP _INTERRUPTS_SYSCALLS_END_SYSCALL
    ._INTERRUPTS_SYSCALLS_SKIP_SYSCALL_FILE_OPEN:

    CMP $CONST_SYSCALL_FILE_CLOSE, %eax
    JNE _INTERRUPTS_SYSCALLS_SKIP_SYSCALL_FILE_CLOSE
    CALL SYSCALLS_FILE_CLOSE
    JMP _INTERRUPTS_SYSCALLS_END_SYSCALL
    ._INTERRUPTS_SYSCALLS_SKIP_SYSCALL_FILE_CLOSE:

    CMP $CONST_SYSCALL_FILE_STAT, %eax
    JNE _INTERRUPTS_SYSCALLS_SKIP_SYSCALL_FILE_STAT
    CALL SYSCALLS_FILE_STAT
    JMP _INTERRUPTS_SYSCALLS_END_SYSCALL
    ._INTERRUPTS_SYSCALLS_SKIP_SYSCALL_FILE_STAT:

    CMP $CONST_SYSCALL_FILE_SEEK, %eax
    JNE _INTERRUPTS_SYSCALLS_SKIP_SYSCALL_FILE_SEEK
    CALL SYSCALLS_FILE_SEEK
    JMP _INTERRUPTS_SYSCALLS_END_SYSCALL
    ._INTERRUPTS_SYSCALLS_SKIP_SYSCALL_FILE_SEEK:

    CMP $CONST_SYSCALL_FILE_CREATE, %eax
    JNE _INTERRUPTS_SYSCALLS_SKIP_SYSCALL_FILE_CREATE
    CALL SYSCALLS_FILE_CREATE
    JMP _INTERRUPTS_SYSCALLS_END_SYSCALL
    ._INTERRUPTS_SYSCALLS_SKIP_SYSCALL_FILE_CREATE:

    CMP $CONST_SYSCALL_FILE_DELETE, %eax
    JNE _INTERRUPTS_SYSCALLS_SKIP_SYSCALL_FILE_DELETE
    CALL SYSCALLS_FILE_DELETE
    JMP _INTERRUPTS_SYSCALLS_END_SYSCALL
    ._INTERRUPTS_SYSCALLS_SKIP_SYSCALL_FILE_DELETE:

    CMP $CONST_SYSCALL_PROCESS_CREATE, %eax
    JNE _INTERRUPTS_SYSCALLS_SKIP_SYSCALL_PROCESS_CREATE
    CALL SYSCALLS_PROCESS_CREATE
    JMP _INTERRUPTS_SYSCALLS_END_SYSCALL
    ._INTERRUPTS_SYSCALLS_SKIP_SYSCALL_PROCESS_CREATE:

    CMP $CONST_SYSCALL_PROCESS_EXIT, %eax
    JNE _INTERRUPTS_SYSCALLS_SKIP_SYSCALL_PROCESS_EXIT
    CALL SYSCALLS_PROCESS_EXIT
    JMP _INTERRUPTS_SYSCALLS_END_SYSCALL
    ._INTERRUPTS_SYSCALLS_SKIP_SYSCALL_PROCESS_EXIT:

    CMP $CONST_SYSCALL_PROCESS_YIELD, %eax
    JNE _INTERRUPTS_SYSCALLS_SKIP_SYSCALL_PROCESS_YIELD
    CALL SYSCALLS_PROCESS_YIELD
    JMP _INTERRUPTS_SYSCALLS_END_SYSCALL
    ._INTERRUPTS_SYSCALLS_SKIP_SYSCALL_PROCESS_YIELD:

    ; TODO handle invalid syscall

    ._INTERRUPTS_SYSCALLS_END_SYSCALL:
    IRET

; collect all the syscall handlers here

    include "os/sos/syscalls/process/create"
    include "os/sos/syscalls/process/exit"
    include "os/sos/syscalls/process/yield"

    include "os/sos/syscalls/file/close"
    include "os/sos/syscalls/file/create"
    include "os/sos/syscalls/file/delete"
    include "os/sos/syscalls/file/open"
    include "os/sos/syscalls/file/read"
    include "os/sos/syscalls/file/seek"
    include "os/sos/syscalls/file/stat"
    include "os/sos/syscalls/file/write"
