
; constants for the syscall number

    const CONST_SYSCALL_FILE_READ = 0
    const CONST_SYSCALL_FILE_WRITE = 1
    const CONST_SYSCALL_FILE_OPEN = 2
    const CONST_SYSCALL_FILE_CLOSE = 3
    const CONST_SYSCALL_FILE_STAT = 4
    const CONST_SYSCALL_FILE_SEEK = 5
    const CONST_SYSCALL_FILE_CREATE = 6
    const CONST_SYSCALL_FILE_DELETE = 7    

    const CONST_SYSCALL_PROCESS_CREATE = 16
    const CONST_SYSCALL_PROCESS_EXIT = 17
    const CONST_SYSCALL_PROCESS_YIELD = 18