.ASSERT_VALID_STACK:
    CMP $CONST_KERNEl_MEMORY_START, %esp
    JG _ASSERT_FAILED
    RET

.ASSERT_EAX_IN_USERSPACE:
    ADD $3, %eax ; TODO handle overflow
    CMP $CONST_KERNEl_MEMORY_START, %eax
    JGE _ASSERT_FAILED
    SUB $3, %eax
    RET

.ASSERT_EBX_IN_USERSPACE:
    ADD $3, %ebx ; TODO handle overflow
    CMP $CONST_KERNEl_MEMORY_START, %ebx
    JGE _ASSERT_FAILED
    SUB $3, %ebx
    RET

.ASSERT_ECX_IN_USERSPACE:
    ADD $3, %ecx ; TODO handle overflow
    CMP $CONST_KERNEl_MEMORY_START, %ecx
    JGE _ASSERT_FAILED
    SUB $3, %ecx
    RET

.ASSERT_EAX_POINTER_IN_USERSPACE:
    CMP $CONST_KERNEl_MEMORY_START, %eax
    JGE _ASSERT_FAILED
    RET

.ASSERT_EBX_POINTER_IN_USERSPACE:
    CMP $CONST_KERNEl_MEMORY_START, %ebx
    JGE _ASSERT_FAILED
    RET

.ASSERT_ECX_POINTER_IN_USERSPACE:
    CMP $CONST_KERNEl_MEMORY_START, %ecx
    JGE _ASSERT_FAILED
    RET

.ASSERT_ZERO_TERMINATED_EAX_FILENAME_IN_USERSPACE:
    PUSH %eax
    CALL _ASSERT_FILENAME_FILENAME_LOOP
    POP %eax
    RET

.ASSERT_ZERO_TERMINATED_EBX_FILENAME_IN_USERSPACE:
    PUSH %eax
    MOV %ebx, %eax
    CALL _ASSERT_FILENAME_FILENAME_LOOP
    POP %eax
    RET

.ASSERT_ZERO_TERMINATED_ECX_FILENAME_IN_USERSPACE:
    PUSH %eax
    MOV %ecx, %eax
    CALL _ASSERT_FILENAME_FILENAME_LOOP
    POP %eax
    RET

._ASSERT_FILENAME_FILENAME_LOOP:
    CALL ASSERT_EAX_IN_USERSPACE
    CMP $0, *%eax
    JE _ASSERT_FILENAME_FILENAME_RETURN
    ADD $1, %eax
    JMP _ASSERT_FILENAME_FILENAME_LOOP
._ASSERT_FILENAME_FILENAME_RETURN:
    RET

._ASSERT_FAILED:
    CALL SYSCALLS_PROCESS_EXIT
    RET